# Generated by Django 2.1.5 on 2019-11-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('img1', models.ImageField(upload_to='media')),
                ('img2', models.ImageField(upload_to='media')),
                ('price', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('available', models.CharField(max_length=200)),
                ('value_for_two', models.IntegerField()),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
