# Generated by Django 2.1.5 on 2019-11-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191118_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category',
            new_name='Pcategory',
        ),
        migrations.AddField(
            model_name='dish',
            name='Scategory',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
