# Generated by Django 2.1.5 on 2019-11-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartObject',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'cartObject',
            },
        ),
    ]
