# Generated by Django 2.1.5 on 2019-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_cartobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartobject',
            name='producttitle',
            field=models.CharField(default=1, max_length=4500),
            preserve_default=False,
        ),
    ]
