# Generated by Django 2.2.7 on 2019-12-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_cartobject_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='onlinefoodorderform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'orderform',
            },
        ),
    ]
