# Generated by Django 2.2.7 on 2019-12-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20191203_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorderform',
            name='phoneno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='onlineorderform',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
